

# POST http://localhost:3000/users/save
# Content-Type: application/json

# {
#     "name":"tina",
#     "email":"tina@gmail.com",
    
# }

# ###
# GET http://localhost:3000/api/users?size=2

# ###

# GET http://localhost:3000/api/users?page=1&size=2
# ###


# GET http://localhost:3000/api/users?page=1&size=2
# ###

# GET http://localhost:3000/api/users?page=2&size=4